---
title: "study_area"
author: "xiaoyi chen"
date: "2024-07-12"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

# data input

```{r}
library(sf)
library(tmap)
library(grid)
library(ggplot2)
library(ggspatial)
library(cowplot)

```

```{r}
# 加载伦敦行政区地图文件
lon_boro <- st_read("D:/File_auto/0_UCL_CASA/OneDrive - University College London/Xiaoyi_dissertation/Analysis/Data/london_boundaries/statistical-gis-boundaries-london/statistical-gis-boundaries-london/ESRI/London_Borough_Excluding_MHW.shp")

# 定义需要绘制的区域
areas_to_plot <- c('City of London', 'Islington', 'Kensington and Chelsea', 'Westminster', 'Camden', 'Lambeth', 'Southwark')

# 筛选需要绘制的区域
filtered_boroughs <- lon_boro[lon_boro$NAME %in% areas_to_plot, ]

```
```{r}
# 设置 tmap 模式为视图
tmap_mode("plot")

# 主图
main_plot <- tm_shape(filtered_boroughs) +
  tm_polygons(col = "#756bb1", border.col = "white", border.lwd = 0.8) +
  tm_layout(frame = FALSE) +
  tm_scale_bar(position = c(0.05, 0.05), text.size = 0.75) +
  tm_compass(north=0,  type = "arrow", position = c("right", "top"))

# 整个伦敦地图的预览图
preview_plot <- tm_shape(lon_boro) +
  tm_polygons(col = "lightgray", border.col = NA) +
  tm_shape(filtered_boroughs) +
  tm_polygons(col = "#756bb1", border.col = "white", border.lwd = 0.5) +
  tm_layout(frame = FALSE)

# 绘制主图
print(main_plot)

# 使用viewport将预览图嵌入主图的右下角
vp <- viewport(x = 0.86, y = 0.29, width = 0.5, height = 0.55)
pushViewport(vp)
print(preview_plot, newpage = FALSE)
popViewport()

```

```{r}
# 设置 tmap 模式为视图
tmap_mode("plot")

# 主图
main_plot <- tm_shape(filtered_boroughs) +
  tm_polygons(col = "#756bb1", border.col = "white", border.lwd = 0.5) +
  tm_layout(frame = FALSE) +
  tm_scale_bar(position = c("left", "bottom")) +
  tm_compass(type = "arrow", position = c("right", "top"))

# 整个伦敦地图的预览图
preview_plot <- tm_shape(lon_boro) +
  tm_polygons(col = "lightgray", border.col = NA) +
  tm_shape(filtered_boroughs) +
  tm_polygons(col = "#756bb1", border.col = "white", border.lwd = 0.5) +
  tm_layout(frame = FALSE)

# 将预览图嵌入主图的右下角
main_plot_with_inset <- main_plot + tm_inset(preview_plot, width = 0.3, height = 0.3, position = c("right", "bottom"))

# 显示组合图
tmap_arrange(main_plot_with_inset)

```


```{r}
# 主图
main_plot <- ggplot() +
  geom_sf(data = filtered_boroughs, fill = "#756bb1", color = "white", size = 0.5) +
  theme_void() +
  theme(plot.margin = unit(c(1, 1, 1, 1), "cm")) +
  annotation_scale(location = "bl", width_hint = 0.5)

# 整个伦敦地图的预览图
preview_plot <- ggplot() +
  geom_sf(data = lon_boro, fill = "lightgray", color = NA) +
  geom_sf(data = filtered_boroughs, fill = "#756bb1", color = "white", size = 0.5) +
  theme_void() +
  theme(plot.margin = unit(c(0, 0, 0, 0), "cm"))

# # 创建指北针
# compass_grob <- grobTree(
#   linesGrob(x = unit(c(0.5, 0.5), "npc"), y = unit(c(0.1, 0.9), "npc"), gp = gpar(col = "black", lwd = 2)),
#   linesGrob(x = unit(c(0.4, 0.5), "npc"), y = unit(c(0.8, 0.9), "npc"), gp = gpar(col = "black", lwd = 2)),
#   linesGrob(x = unit(c(0.6, 0.5), "npc"), y = unit(c(0.8, 0.9), "npc"), gp = gpar(col = "black", lwd = 2)),
#   textGrob("N", x = unit(0.5, "npc"), y = unit(0.95, "npc"), gp = gpar(col = "black", fontsize = 12, fontface = "bold"))
# )

# 将预览图添加到主图的右下角
combined_plot <- ggdraw() +
  draw_plot(main_plot) +
  draw_plot(preview_plot, x = 0.7, y = 0.05, width = 0.25, height = 0.25) +
  draw_grob(compass_grob, x = 0.85, y = 0.75, width = 0.1, height = 0.2)

# # 添加比例尺
# combined_plot <- main_plot_with_inset + annotation_scale(location = "bl", width_hint = 0.5)

# 打印最终图像
print(combined_plot)

```


```{r}
# 主图
main_plot <- ggplot() +
  geom_sf(data = filtered_boroughs, fill = "#756bb1", color = "white", size = 0.5) +
  theme_void() +
  theme(plot.margin = unit(c(1, 1, 1, 1), "cm")) +
  annotation_scale(location = "br", width_hint = 0.5) +
  annotation_north_arrow(location = "tr", which_north = "true", 
                         pad_x = unit(0.5, "cm"), pad_y = unit(0.5, "cm"),
                         style = north_arrow_fancy_orienteering)

# 整个伦敦地图的预览图
preview_plot <- ggplot() +
  geom_sf(data = lon_boro, fill = "lightgray", color = NA) +
  geom_sf(data = filtered_boroughs, fill = "#756bb1", color = "white", size = 0.5) +
  theme_void() +
  theme(plot.margin = unit(c(0, 0, 0, 0), "cm"))

# 把预览图加到主图的右下角
inset_grob <- ggplotGrob(preview_plot)
main_plot_with_inset <- main_plot + 
  annotation_custom(grob = inset_grob,
                     xmin = 0.7, xmax = 1.2, ymin = -0.3, ymax = 0.2)

# 添加比例尺
main_plot_with_scale <- main_plot_with_inset + annotation_scale(location = "bl", width_hint = 0.5)

# 绘制最终图像
print(main_plot_with_inset)

```

